{% set version = "2.3.27" %}

package:
  name: dials-data
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dials_data/dials_data-{{ version }}.tar.gz
  sha256: 2a0d4140c4a309e71d19b46e34a99b3a6d0d01f26828ea60ae55a397bfcb0dc7

build:
  number: 0
  noarch: python
  entry_points:
    - dials.data = dials_data.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - importlib_resources
    - py
    - pytest
    - python >=3.7
    - pyyaml

test:
  imports:
    - dials_data
  commands:
    - pip check
    - dials.data --help
    - dials.data list
  requires:
    - pip

about:
  home: https://pypi.org/project/dials-data
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: DIALS Regression Data Manager

  description: |
    A python package providing data files used for regression tests in
    scientific software processing crystallographic data, such as DIALS,
    dxtbx, xia2, and related packages.
  doc_url: https://dials-data.readthedocs.io/
  dev_url: https://github.com/dials/data

extra:
  recipe-maintainers:
    - rjgildea
    - ndevenish
    - anthchirp
