{% set name = "dials-data" %}
{% set version = "2.1.41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dials_data/dials_data-{{ version }}.tar.gz
  sha256: 51db7289593a05f9f80b35e582005a7f0feb4c562168729391eaf0c75d4e95ef

build:
  number: 0
  noarch: python
  entry_points:
    - dials.data = dials_data.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - importlib_resources
    - py
    - pytest
    - python >=3.6
    - pyyaml

test:
  imports:
    - dials_data
  commands:
    - dials.data --help
    - dials.data list

about:
  home: https://github.com/dials/data
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: DIALS Regression Data Manager

  description: |
    A python package providing data files used for regression tests in
    scientific software processing crystallographic data, such as DIALS,
    dxtbx, xia2, and related packages.
  doc_url: https://dials-data.readthedocs.io/
  dev_url: https://github.com/dials/data

extra:
  recipe-maintainers:
    - anthchirp
